version: '3'

services:
  db:
    container_name: mysql
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      # MYSQL_DB: ${DATABASE_DB}
      # MYSQL_USER: ${DATABASE_USER}
      # MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306" # ${DATABASE_PORT}
    volumes:
      - mysql-blog-data:/var/lib/mysql


volumes:
  mysql-blog-data: